from context.base_context import BaseObjectiveContext
from context.flexible import FlexibleObjectiveContext

# Context traffic densities
TRAFFIC_LOW = BaseObjectiveContext.TRAFFIC_LOW
TRAFFIC_HIGH = BaseObjectiveContext.TRAFFIC_HIGH
TRAFFIC_RANDOM = BaseObjectiveContext.TRAFFIC_RANDOM

# Predefined distributions for FlexibleObjectiveContext
FLEXIBLE_ONLY_SMALL_SHIPS = FlexibleObjectiveContext.FLEXIBLE_ONLY_SMALL_SHIPS
FLEXIBLE_ONLY_MEDIUM_SHIPS = FlexibleObjectiveContext.FLEXIBLE_ONLY_MEDIUM_SHIPS
FLEXIBLE_ONLY_LARGE_SHIPS = FlexibleObjectiveContext.FLEXIBLE_ONLY_LARGE_SHIPS
FLEXIBLE_ALL_SHIPS_EVENLY = FlexibleObjectiveContext.FLEXIBLE_ALL_SHIPS_EVENLY

